apiVersion: apps/v1
kind: Deployment
metadata:
  name: usama-22012-redis-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: redis-pod
  template:
    metadata:
      labels:
        name: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2012
